### ISSUE TITLE
ldap_add(): Add: Invalid DN syntax 

### ISSUE THREAD

**Issue by ducdung0909** [lota/phamm#13]
Dear team,
    I have installed phamm 0.6.5 and ldap on Ubuntu 14.04 machine but I can't create a new domain after I log in as admin. I got error log in apache2 as below : 
#### 

[Mon May 16 11:18:52.067787 2016] [:error] [pid 22472] [client 172.16.10.1:54081] PHP Warning:  ldap_add(): Add: Invalid DN syntax in /var/www/html/phamm/lib/ldap.php on line 119, referer: http://172.16.10.12/phamm/public/main.php
[Mon May 16 11:18:52.068535 2016] [:error] [pid 22472] [client 172.16.10.1:54081] PHP Warning:  ldap_add(): Add: Invalid DN syntax in /var/www/html/phamm/lib/ldap.php on line 119, referer: http://172.16.10.12/phamm/public/main.php
[Mon May 16 11:18:52.069057 2016] [:error] [pid 22472] [client 172.16.10.1:54081] PHP Warning:  ldap_add(): Add: Invalid DN syntax in /var/www/html/phamm/lib/ldap.php on line 119, referer: http://172.16.10.12/phamm/public/main.php
### 

 I have configured ldap as example instruction.

**Comment by lota** [comment]
Check your ldap setup and the LDAP_BASE in your config.inc.php

HTH
Alessandro
