### ISSUE TITLE
Password truncate without warning

### ISSUE THREAD

**Issue by Sjd-Risca** [lota/phamm#14]
The files _views/helpers.php:699_ and _view/helper.php:678_ create the input type for inserting the password with the attributes `size="15" maxlength="15"`.

Problem arises when a user inserts a password longer than that: it is silently truncate and then updated without any warning.

I would suggest to add the following implementations:
- create a warning if the password is longer than that;
- add a field in pham config for setting longer passwords;

What do you think about?

---

**addendum**: I notice that no more dots are added when the limit of 15 chars is reached, but I thing that is not really easy to be noticed by the users.

**Comment by lota** [comment]
With a commit on Thu Feb 19 15:07:54 2015 +0100 maximum password length within forms increased from 15 to 50

**Comment by benben159** [comment]
I think maximum password length must be configurable in config.inc.php. correct me if i am wrong.

**Comment by lota** [comment]
Hi Benediktus,
could be a useful features, something like PASSWORD_MIN_LENGHT

// Min password length
define ('PASSWORD_MIN_LENGHT',3);

**Comment by lota** [comment]
thanks for report, but Phamm is no longer supported,
we evaluate pull request only
