### ISSUE TITLE
Feature request: Password strength

### ISSUE THREAD

**Issue by agabellini** [lota/phamm#17]
What about the possibility to force new passwords to contain special character,
uppercase letters or numbers?

Andrea

**Comment by lota** [comment]
this feature require to improve the wrong_pw() function defined in controllers/helpers.php

at this time wrong_pw()  only check password match and password lenght

**Comment by wdouglascampbell** [comment]
I have submitted pull request #25 which addresses this need.

**Comment by lota** [comment]
merged
