### ISSUE TITLE
Javascript error 

### ISSUE THREAD

**Issue by cosmox** [lota/phamm#3]
Time: 30.07.2015 12:45:07
Error: TypeError: f is null
Source: http://demo.phamm.org/phamm/functions.js
Line: 35

phamm Version: 0.6.2

The Javascript should be fired after the page is completly loaded.
If you don't like Jquery you can do this by the oldscool :

<body onload="myFunction()">

Or you use another crossbrowser solution, but i guess jquery can be a good basic for all your frontend issues

**Comment by cosmox** [comment]
Okay i take a deeper look at this Problem, i guess you try to disable the autocomplete function for the login form. You'r looking for an Element with the ID login, but the Loginform has no ID, so you will never found the form.

The simple solution is to set the attribute "autocomplete=off" into the form tag.

If you prefer the JS way and dont use an ID you should better use the form.name selector

document.forms.login.autocomplete = "off";

**Comment by lota** [comment]
Hi Cosmox, sorry for big delay!

I also not like autocomplete with in password field and "autocomplete=off" is the simplest solutiin, anyway some year ago this not validate XHTML, at this time I think will be introduce the attribute. Please if you want do a pull request ;-)

cheers
Alessandro

**Comment by cosmox** [comment]
Hi Lota, 

no Problem

best regards

**Comment by lota** [comment]
thanks for report, but Phamm is no longer supported,
we evaluate pull request only
