### ISSUE TITLE
localisation is not working

### ISSUE THREAD

**Issue by cosmox** [lota/phamm#4]
If i chang the Language Select, nothing is happen.
So i test it again with your Demo, but the behavior is the same, after changing the language selector, nothing is happen.

Tips and hints are welcome

**Comment by lota** [comment]
Check if language wanted inatalled on system. Phamm use gettext.

HTH
Alessandro

Inviato con AquaMail per Android
http://www.aqua-mail.com

Il 30 luglio 2015 13:08:45 Michael Kasten notifications@github.com ha 
scritto:

**Comment by cosmox** [comment]
Hi lota,
yes gettext is installed
$ locale -a
C
C.UTF-8
de_DE.utf8
en_US.utf8
POSIX
and the language files are also available.

But what is with your own Demo?

**Comment by lota** [comment]
Hi Cosmox,
I compiled all locales in http://demo.phamm.org/phamm/
alfter a apache2 restart all works fine:

![ru](https://cloud.githubusercontent.com/assets/956392/13051889/f6752fda-d3fb-11e5-863b-1dfe5850a8ba.png)

on Debian

dpkg-reconfigure locales

/etc/init.d/apache2 restart

HTH
Alessandro

**Comment by lota** [comment]
Anyway, some lemma could be not translated, in this case default language (English) appears. Please consider to update locale files and contribute to Phamm.
