### ISSUE TITLE
Question about Password length

### ISSUE THREAD

**Issue by cosmox** [lota/phamm#5]
Hi, there is a limit of 15 chars on the Password field, that can be confusing.
If the user generates a password with more than 15 chars, and copy them into the password field, the password is cutting to a length of 15 chars. So if the user try to login with his own password the passwords will never match.
Is there a special reason with LDAP thats need a max length of 15 chars?

**Comment by lota** [comment]
In source maxlength is now 50, anyway. 
Anyway there are real limits on unix systems for max password length. 

http://superuser.com/questions/148971/what-is-the-max-length-of-password-on-unix-linux-system

**Comment by lota** [comment]
thanks for report, but Phamm is no longer supported,
we evaluate pull request only
