### ISSUE TITLE
Should inetLocalMailRecipient be used when creating new domains?

### ISSUE THREAD

**Issue by jgrowl** [lota/phamm#6]
In public/main.php, inetLocalMailRecipient is used when creating a new domain:
https://github.com/lota/phamm/blob/67901a37920ace8b7863e90c6cccf285434d0139/public/main.php#L291

inetLocalMailRecipient seems to come from misc.schema, but misc.schema conflicts with ISPEnv2.schema. Is there something I'm missing here?

I am getting an object not found when trying to create a new domain. If I comment that line out in main.php, the domain gets added without issue. If I try to add misc, then I get errors trying to include ISPEnv2.

Should the inetLocalMailRecipient be there at all? I notice that in the example mail.ldif the domain object does not use it.

https://github.com/lota/phamm/blob/67901a37920ace8b7863e90c6cccf285434d0139/examples/ldif/sample-mail.ldif#L3

I am not very proficient with LDAP in general so I am not sure if I am missing something. Sorry if this is a silly question.

**Comment by lota** [comment]
thanks for report, but Phamm is no longer supported,
we evaluate pull request only
