### ISSUE TITLE
SECURITY: Wrong check on max_accounts_allowed

### ISSUE THREAD

**Issue by Sjd-Risca** [lota/phamm#9]
I noticed that the check on **maximum allowed account** is only on the level of the web interface: only when on the web interface is pushed the button "Add new account" the code checks whether the number of allowed alias is overtaken and if it is, then the mask for adding new alias is blocked.

I think that this is not enough because the **user can pass this type of control** simply by manually pushing a custom http POST request with the required data. To be safe the control on the maximum number of alias should be performed whenever there is a ldap_add query from any legitimated user (inside of the **case "insert_account"** clause)!
`$r = PhammLdap::phamm_add ('mail='.$mail.',vd='.$domain.','.LDAP_BASE,$entry);`

The following shell example works for whichever maxAlias is set (only the cookies line needs to be change accordlying to a valid user session):
`
$ wget --post-data "action=insert_account&account_new=useralias%40examplet.tld&password1=ccc&password2=ccc&givenname=cc&sn=cc&confirm%5B%5D=alias&values_multi%5Balias%5D%5Bmaildrop%5D=admin&values%5Balias%5D%5Baccountactive%5D=TRUE&values%5Balias%5D%5Bsmtpauth%5D=FALSE&values%5Balias%5D%5Bamavisbypassviruschecks%5D=TRUE&values%5Balias%5D%5Bamavisbypassspamchecks%5D=TRUE&values%5Bproxy%5D%5Bwebaccess%5D=TRUE&values%5Bproxy%5D%5Bproxyhost%5D=&values%5Bperson%5D%5Btelephonenumber%5D=&values%5Bperson%5D%5Bhomephone%5D=&values%5Bperson%5D%5Bmobile%5D=&values%5Bperson%5D%5Bfacsimiletelephonenumber%5D=&values%5Bperson%5D%5Bpager%5D=&values%5Bdavical%5D%5Bcaldavaccess%5D=TRUE" --header "Cookie: PHPSESSID=a0lfboqfpjn5hr68uabt8mur35; 5d89dac18813e15aa2f75788275e3588=ef6nq8oda14rdt3pa8bhgv6h77; collapsedNodes=" --header "Location: http://127.0.0.1/phamm/main.php?action=domain_view&amp;domain=examplet.tld" http://127.0.0.1/phamm/main.php
`

--- More datails ---
Using phamm version:

```
$ apt-cache policy phamm
phamm:
  Installed: 0.6.2-1.2
  Candidate: 0.6.2-1.2
  Version table:
 *** 0.6.2-1.2 0
        500 http://http.debian.net/debian/ jessie/main amd64 Packages
```

**Comment by lota** [comment]
In effect some limitations about max\* attributes are tested only on web interface. Your discussion is interesting, I will investigate about.

Thanks
Alessandro

**Comment by lota** [comment]
thanks for report, but Phamm is no longer supported,
we evaluate pull request only
